version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/streaming
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=streaming
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: 